# Generated by Django 4.0.6 on 2022-10-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='count_reviews',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_url',
            field=models.URLField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
