# Generated by Django 4.0.6 on 2022-11-02 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
